name: ivangram
options:
  bundleIdPrefix: com.maga4208
  deploymentTarget:
    iOS: 15.0
targets:
  ivangram:
    type: application
    platform: iOS
    sources: [TelegramApp]
    dependencies:
      - framework: Frameworks/TDLibFramework.xcframework
    settings:
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Frameworks
      HEADER_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Frameworks/TDLibFramework.xcframework/Headers
      OTHER_LDFLAGS: $(inherited) -framework TDLibFramework
    info:
      path: TelegramApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: ivangram
        CFBundleDisplayName: ivangram
